# Which C++ compiler to use, default is Gnu g++
CXX         = g++
# Where is the Synarmosma library located?
SYNARMOSMA  = $(HOME)/fabrica/local
# General flags for C++ compilation, assumes compiler with OpenMP support
CXX_FLAGS   = -Wall -std=c++14 -fopenmp -march=native -I$(SYNARMOSMA)/include -fPIC
# For debug mode
DEBUG       = -g -DDEBUG
# Optimization values for the g++ on an x86-64 platform
OPT         = -O3 -fstrict-aliasing -ftree-vectorize -funroll-loops
# Choose either the debug or optimized version of the library
CXX_FLAGS  += $(OPT)
#CXX_FLAGS  += $(DEBUG)
# Verbose output
#CXX_FLAGS  += -DVERBOSE
# Use the 64 bit integer versions of the vertex energy and spatial geometry?
# If the Synarmosma library was compiled with this flag, then the Diaplexis
# library must be as well.
#CXX_FLAGS += -DDISCRETE
# Standard linking flags, shouldn't need to be changed
LD_FLAGS    = -L$(SYNARMOSMA)/lib -Wall -shared -fopenmp
# Debug or optimized version for linking...
LD_FLAGS   += $(OPT)
#LD_FLAGS   += $(DEBUG)
# All the necessary libraries: Synarmosma, PugiXML and the standard math library.
LIBS        = -lsynarmosma -lpugixml -lm
# Where to install the Diaplexis library
INSTALL_DIR = $(HOME)/fabrica/local